### ISSUE TITLE
EE project must be specified on sd-gpu

### ISSUE THREAD

**Issue by tcnichol** [awi-response/darts-nextgen#77] opened 2024-12-02 21:04 UTC
At least when trying to run on sd-gpu, it seems that the pipeline throws an error without an earth engine project id. 

Current workaround is adding a new script

/darts-nextgen/darts/src/darts/run_native.py 

and passing that variable inside the method, or by adding ee-project to the

planet_config.toml

**Comment by iona5** [comment] 2024-12-03 06:24
the pipeline is currently supposed to get a GEE project either by specifiying it in the config or cli argument or by having it configured during the Google Earth Engine authentication (so for example with `earthengine authenticate --auth_mode notebook` .

**Comment by relativityhd** [comment] 2024-12-03 09:46
This is the desired behavior and not a bug, closing.

**Closed by relativityhd** 2024-12-03 09:46 UTC
Labels: bug
